from typing import List, Tuple

# Cabecalho das funcoes para a IDE reconhecer
def linearFunction(x_values: List[float], a: float, b: float) -> List[float]:
    ...
def costFuctionLinear(x_values: List[float], y_values: List[float], a: float, b: float) -> float:
    ...
def gradientLinear(x_values: List[float], y_values: List[float], a: float, b: float, learn: float, steps: int) -> Tuple[float, float]:
    ...
def quadraticFunction(x_values: List[float], a: float, b: float, c: float) -> List[float]:
    ...
def costFuctionQuadratic(x_values: List[float], y_values: List[float], a: float, b: float, c: float) -> float: 
    ...
def gradientQuadratic(x_values: List[float], y_values: List[float], a: float, b: float, c: float, learn: float, steps: int) -> Tuple[float, float, float]: 
    ...